version: '3.8'

services:
  cineverse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cineverse-3d-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./backend/data:/app/backend/data
